/*
  TODO:
  break down into multiple components for the one pager
  tidy up formatting
  update icons for cards
  fix large padding below pfp :: required new section
  deploy via GitHub workflows

  add nav bar that moves down page (anchors?) when clicked
  move dark mode out of nav and nav into nav.js
*/

import Head from "next/head";
import { useState } from "react";
import {
  AiFillGithub,
  AiOutlineUnorderedList
} from "react-icons/ai";
import {
  BsFillMoonStarsFill
} from "react-icons/bs";

// component imports
import facts from "../components/facts.js"
import header from "../components/header.js";
import skills from "../components/skills.js";
import portfolio from "../components/portfolio.js";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Elena Thomas - DevSecOps Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 dark:text-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-12">
            <div className="flex justify-start">
              <ul>
                <AiOutlineUnorderedList
                  className="text-2xl cursor-pointer"
                />
              </ul>
            </div>
            <div className="flex justify-end">
              <ul>
                  <li>
                  <BsFillMoonStarsFill
                      onClick={() => setDarkMode(!darkMode)}
                      className="cursor-pointer text-2xl"
                  />
                  </li>
              </ul>
            </div>
          </nav>
          {header()}
        </section>
        <section>
          {facts()}
        </section>
        <section>
          {skills()}
        </section>
        <section>
          {portfolio()}
        </section>
      </main>
      <footer className=" pb-10 pl-5 bg-white dark:bg-gray-900 md:pl-10 lg:pl-20 dark:text-white">
        <div className=" text-black dark:text-slate-200">
          <a href="https://github.com/lenakita/portfolio-website">
            <AiFillGithub className="cursor-pointer"/>
          </a>
        </div>
        <p className="text-md md:text-lg">Made using:</p>
        <ul>
          <li className="text-teal-600 dark:text-teal-200">
            <a href="https://nextjs.org/">Next.js</a>
          </li>
          <li className="text-teal-600 dark:text-teal-200">
            <a href="https://tailwindcss.com">Tailwind CSS</a>
          </li>
        </ul>
      </footer>
    </div>
  );
}
